plugins {
    id 'application'
    id 'strife.conventions'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'com.strife.tools.datagen.DataGenMain'
}

dependencies {
    testImplementation "org.junit.jupiter:junit-jupiter:${providers.gradleProperty('junit_version').get()}"
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

def repoRoot = rootProject.projectDir.parentFile

run {
    workingDir = repoRoot
    args = [
            '--tables-root',
            file("${repoRoot}/tables").toString(),
            '--resources-root',
            project(':content-base').file('src/main/resources').toString()]
}
